### PR TITLE
Added Pulp's WhiskasModel2 example

### PR DESCRIPTION
**Pull request by jonahgeorge**
While evaluating your project I was looking for a slightly more advanced example. This commit adds Pulp's [WhiskasModel2](https://github.com/coin-or/pulp/blob/master/examples/WhiskasModel2.py) example to show the differences between Rulp and Pulp syntax.

### CODE REVIEW

**Comment by wouterken** [comment]
Hi Jonah,

Thanks for your contribution. It's nice to see a more complex example in there.

I'm not sure the syntax for the cost and percentage hashes you are creating is correct. It looks like you may be combining the string and hash key syntax. Perhaps you meant something like the following?

``` ruby
costs           = {Chicken: 0.013, Beef: 0.008, Mutton: 0.010, Rice: 0.002, Wheat: 0.005, Gel: 0.001}
protein_percent = {Chicken: 0.100, Beef: 0.200, Mutton: 0.150, Rice: 0.000, Wheat: 0.040, Gel: 0.000}
fat_percent     = {Chicken: 0.080, Beef: 0.100, Mutton: 0.110, Rice: 0.010, Wheat: 0.010, Gel: 0.000}
fibre_percent   = {Chicken: 0.001, Beef: 0.005, Mutton: 0.003, Rice: 0.100, Wheat: 0.150, Gel: 0.000}
salt_percent    = {Chicken: 0.002, Beef: 0.005, Mutton: 0.007, Rice: 0.002, Wheat: 0.008, Gel: 0.000}
```

**Comment by jonahgeorge** [comment]
I was initially using string keys because I didn't see that `Constant_i == Constant`.

I'm curious though, this doesn't seem entirely consistent in practice:

``` ruby
# When using LV variables as keys to a hash, fails without the explicit call to `i.name`:

ingredients = [Chicken_i, Beef_i, Mutton_i, Rice_i, Wheat_i, Gel_i]
costs = {Chicken: 0.013, Beef: 0.008,  ... }
# Redacted for brevity
objective = ingredients.map{|i| costs[i] * i}.inject(:+)
# objective = ingredients.map{|i| costs[i.name] * i}.inject(:+)
```

``` ruby
# When getting the value of an LV variable, fails without the `_i` suffix:

ingredients = [Chicken_i, Beef_i, Mutton_i, Rice_i, Wheat_i, Gel_i]
# Redacted for brevity
puts "Chicken: #{Chicken.value}"
# puts "Chicken: #{Chicken_i.value}"
```

**Comment by jonahgeorge** [comment]
Could it make more sense to explicitly define an LV variable `chicken = Rulp::Variable(args)`?

**Comment by wouterken** [comment]
Sorry for the confusion. `Constant_i` is not equal to `Constant`. In the hash example I gave you the keys are actually symbols - I can understand how the capitalisation of the symbols can make it look like a constant . 
E.g 

``` ruby
{Chicken: 0.013}.keys.first == :Chicken # (Not a constant, but a symbol).
```

In ruby if you use `:` as your key/value delimiter your keys will always be a symbol.
If you use the `=>` delimiter you can use keys of any type.

So if you wish to have the variables as keys in your hash you will need to use the rocket syntax to declare your hash instead. 
E.g

``` ruby
ingredients     = [Chicken_i, Beef_i, Mutton_i, Rice_i, Wheat_i, Gel_i]
costs           = {Chicken_i => 0.013, Beef_i => 0.008, Mutton_i => 0.010, Rice_i => 0.002, Wheat_i => 0.005, Gel_i => 0.001}
protein_percent = {Chicken_i => 0.100, Beef_i => 0.200, Mutton_i => 0.150, Rice_i => 0.000, Wheat_i => 0.040, Gel_i => 0.000}
fat_percent     = {Chicken_i => 0.080, Beef_i => 0.100, Mutton_i => 0.110, Rice_i => 0.010, Wheat_i => 0.010, Gel_i => 0.000}
fibre_percent   = {Chicken_i => 0.001, Beef_i => 0.005, Mutton_i => 0.003, Rice_i => 0.100, Wheat_i => 0.150, Gel_i => 0.000}
salt_percent    = {Chicken_i => 0.002, Beef_i => 0.005, Mutton_i => 0.007, Rice_i => 0.002, Wheat_i => 0.008, Gel_i => 0.000}
```

Then you can get away with not using `i.name`
E.g

``` ruby
objective = ingredients.map{|i| costs[i] * i}.inject(:+)
```

**Comment by jonahgeorge** [comment]
You learn something every day :smile: 

I've switched the hash definitions to use symbols. Is there anything else that stands out to you?

**Comment by wouterken** [comment]
:+1: This looks good - thanks for your contribution :smile:

**Pull request merged**
